# permissions for end users to view kubernetesauthbackendroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubernetesauthbackendrole-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vault-controller
    app.kubernetes.io/part-of: vault-controller
    app.kubernetes.io/managed-by: kustomize
  name: kubernetesauthbackendrole-viewer-role
rules:
- apiGroups:
  - vault.qts.cloud
  resources:
  - kubernetesauthbackendroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.qts.cloud
  resources:
  - kubernetesauthbackendroles/status
  verbs:
  - get
